server:
  port: 8081

#redis配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    pool:
      max-idle: 1000
      min-idle: 5
      max-active: 1000
      max-wait: 10000
  #rabbitmq配置 
  rabbitmq:
    host: 192.168.100.220
    port: 5672
    username: admin
    password: 5672