server:
  port: 8081

#redis配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    pool:
      max-idle: 1000
      min-idle: 5
      max-active: 1000
      max-wait: 10000
  #rabbitmq配置 
  rabbitmq:
    host: 192.168.100.220
    port: 5672
    username: admin
    password: 5672
  #配置mybatis多数据源
  datasource:
    test1:
      url: jdbc:mysql://localhost:3306/test1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    test2:
      url: jdbc:mysql://localhost:3306/test2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver